services:

  postgres:
    image: postgres:17

    container_name: hospital-archive-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - archive_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine

    container_name: hospital-archive-redis

    restart: unless-stopped

    command:
      redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - archive_redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: hospital-archive-backend

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_URL: redis://redis:6379/0

    volumes:
      - archive_documents:/app/storage

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    expose:
      - "8000"


  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: hospital-archive-worker

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_URL: redis://redis:6379/0

    command:
      [
        "celery",
        "-A",
        "app.tasks.celery_app.celery_app",
        "worker",
        "--loglevel=info"
      ]

    volumes:
      - archive_documents:/app/storage

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: hospital-archive-frontend

    restart: unless-stopped

    ports:
      - "8080:80"

    depends_on:
      - backend



  cloudflared:
    image: cloudflare/cloudflared:latest

    container_name: hospital-archive-cloudflared

    restart: unless-stopped

    command:
      tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}

    depends_on:
      - frontend

   
volumes:

  archive_postgres_data:

  archive_redis_data:

  archive_documents: