"""add soft delete to documents

Revision ID: 07c1b5d7759e
Revises: 6d6b8aaff8f7
Create Date: 2026-09-02 23:19:07.738990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c1b5d7759e'
down_revision: Union[str, Sequence[str], None] = '6d6b8aaff8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
