"""link document to hospitalization

Revision ID: 5301b6fe4fd3
Revises: a4357127e225
Create Date: 2026-08-16 16:22:15.309650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5301b6fe4fd3'
down_revision: Union[str, Sequence[str], None] = 'a4357127e225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'hospitalization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'hospitalization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
