"""add archived at to document model

Revision ID: 988d0bb383a5
Revises: 4596f19b7cd3
Create Date: 2026-08-17 18:54:26.318049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988d0bb383a5'
down_revision: Union[str, Sequence[str], None] = '4596f19b7cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'archived_at')
    # ### end Alembic commands ###
