"""link documents to unique hospitalizations

Revision ID: cf698bf6e669
Revises: 5301b6fe4fd3
Create Date: 2026-08-16 16:44:28.449154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf698bf6e669'
down_revision: Union[str, Sequence[str], None] = '5301b6fe4fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['hospitalization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    # ### end Alembic commands ###
