"""add admission and discharge dates to ai result

Revision ID: fd779eb78b58
Revises: cf698bf6e669
Create Date: 2026-08-17 02:07:46.682362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd779eb78b58'
down_revision: Union[str, Sequence[str], None] = 'cf698bf6e669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ai_results', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('document_ai_results', sa.Column('discharge_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_ai_results', 'discharge_date')
    op.drop_column('document_ai_results', 'admission_date')
    # ### end Alembic commands ###
